version: "2"

services:
  web:
    build: .
    image: hoodies/web
    container_name: hoodies-web
    command: bash -c "rackup -p 8090"
    volumes: &web-volumes
      - ./:/app
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - "8090:8090"
    environment: &web-environment
      RACK_ENV: development
